# Generated by Django 5.2.12 on 2026-04-22 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researcherprofile',
            old_name='resarch_area',
            new_name='research_area',
        ),
    ]
